substitutions:
  name: "red-smartknobty"
  friendly_name: "RedSmartKnob"
  comment: ESP Smart Knob
  # Your weather entity in Home Assistant
  weather: weather.forecast
  # Your indoor temperature entity in Home Assistant
  indoor_temp_entity: sensor.indoor_temperature
  homeassistant_base_uri: "https://homeassistant.example.com"
  theme: "blue"  # blue, orange, green, white

  # Set to true if you want a local sendspin client, rather than controlling a remote mediaplayer.
  enable_sendspin: true
  # The media player entity to control. If using `enable_sendspin`, this should
  # refer to the Music Assistant version of the entity, not the device
  # directly.
  mediaplayer: media_player.office

  api_encryption_key: !secret api_encryption_key
  ota_password: !secret ota_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_api_fallback_password: !secret wifi_api_fallback_password

packages:
  # For local development, use:
  #RedSmartKnob: !include RedSmartKnob/packages.yaml
  # Otherwise, this will pull it from GitHub:
  RedSmartKnob:
    url: https://github.com/magdalar/RedSmartKnob
    files: [RedSmartKnob/packages.yaml]
    ref: main
    refresh: 0s  # always pull, comment out for caching
 
# vim: set tabstop=2 shiftwidth=2 expandtab:
