# Guition 1.8" Silver Puck, JC3636W518C_I_Y
substitutions:
  name: "silverpuck-sendspin"
  friendly_name: "SilverPuck"
  comment: "Sendspin-mode Guition 1.8in Silver Puck JC3636W518C_I_Y"

  # Use silverpuck.controls.dev.yaml for controls-mode.
  enable_sendspin: true

  repo_base_uri: "../../RedSmartKnob"

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
api:
  encryption:
    key: !secret api_encryption_key
ota:
  - platform: esphome
    password: !secret ota_password

packages:
  setup: !include device/packages.yaml
 
# vim: set tabstop=2 shiftwidth=2 expandtab:
