# Guition 1.8" Silver Puck, JC3636W518C_I_Y
substitutions:
  name: "silverpuck-sendspin"
  friendly_name: "SilverPuck"
  comment: "Sendspin-mode Guition 1.8in Silver Puck JC3636W518C_I_Y"

  # Provide a local sendspin client. Media controls will control that, not a
  # remote player.
  enable_sendspin: true

  #repo_base_uri: "../../RedSmartKnob"

# Duplicated for the sake of ewt-gen
esphome:
  name: "${name}"

logger:
  level: INFO

packages:
  setup:
    url: https://github.com/magdalar/RedSmartKnob
    files: [devices/guition-silverpuck-jc3636w518c/device/packages.yaml]
    refresh: 0s  # always pull, comment out for caching
 
# vim: set tabstop=2 shiftwidth=2 expandtab:
