# This unit connects the UI and the media player.
# It does not directly reference the media player entity, as both a local
# sendspin player and a remote HA media player are supported. Instead, scripts
# are used to abstract the API.
# The `handle_media_*` scripts are used to provide data _to_ the UI.
# The `set_media_*` scripts are used to send commands to the media player.

globals:
  - id: current_volume
    type: float
    initial_value: '0.5'  # Default fallback volume

  - id: last_posted_position_secs
    type: int
    initial_value: '-1'
  - id: last_posted_duration_secs
    type: int
    initial_value: '-1'

text:
  - platform: template
    name: "Music Assistant Media Player Entity"
    id: preference_media_player_entity
    entity_category: config
    mode: text
    initial_value: "${mediaplayer}"
    restore_value: true
    set_action:
      - lambda: |-
          if (x.empty() || x == id(preference_media_player_entity).state) {
            // It's good, but nothing needs to change.
            id(preference_media_player_entity).publish_state(x);
            return;
          }
          if (!x.starts_with("media_player.")) {
            // It's bad, reject it. Don't need to reboot.
            ESP_LOGW("actions_time", "Rejecting invalid media_player entity; must start with \"media_player.\"; found: %s", x.c_str());
            id(preference_media_player_entity).publish_state(id(preference_media_player_entity).state);
            return;
          }
          // New value accepted, ask for a reboot.
          id(preference_media_player_entity).publish_state(x);
          ESP_LOGI("actions_media", "New media_player entity: %s. Will request reboot.", x.c_str());
          id(slow_trigger_reboot_sequence)->execute();

esphome:
  on_boot:
    # HA sensors setup runs at AFTER_CONNECTION (100). So long as we run after
    # DATA (600), we should be good.
    - priority: 300
      then:
        # Media Player Entity
        - lambda: |-
            // Static as set_entity_id takes the c_str pointer.
            static const std::string new_entity = id(preference_media_player_entity).state;
            if (!new_entity.empty()) {
              id(set_mediaplayer_entity_id)->execute(new_entity.c_str());
              id(preference_media_player_entity).publish_state(new_entity);
            }

script:
  - id: handle_media_album_art_display_placeholder
    then:
      - lvgl.image.update:
          id: album_cover_image_overlay
          src: album_placeholder

  - id: handle_media_album_art_display
    parameters:
      art_source: esphome::image::Image*
    then:
      - if:
          condition:
            lambda: 'return id(album_art_preference).state;'
          then:
            - lambda: |-
                ESP_LOGD("actions_media", "Album art downloaded!");
            - lvgl.image.update:
                id: album_cover_image_overlay
                src: !lambda "return art_source;"
          else:
            - script.execute: handle_media_album_art_display_placeholder

  - id: handle_media_progress
    parameters:
      position_secs: float
      duration_secs: float
    then:
      - lambda: |-
          if (position_secs == id(last_posted_position_secs)
              && duration_secs == id(last_posted_duration_secs)) {
            return;
          }
          if (duration_secs != id(last_posted_duration_secs)) {
            ESP_LOGD("actions_media", "New track duration: %.1f", duration_secs);
          }
          id(last_posted_position_secs) = position_secs;
          id(last_posted_duration_secs) = duration_secs;

          float progress_percent =
            duration_secs > 0.0 ? (position_secs / duration_secs * 100.0) : 0.0;
          lv_arc_set_value(id(track_progress_arc_overlay), progress_percent);

          // --- FORMAT AND UPDATE THE TEXT LABEL ---
          // Break down position into minutes and seconds
          int pos_min = (int)position_secs / 60;
          int pos_sec = (int)position_secs % 60;

          // Break down duration into minutes and seconds
          int dur_min = (int)duration_secs / 60;
          int dur_sec = (int)duration_secs % 60;
          if (pos_sec % 10 == 0) {
            ESP_LOGD("actions_media", "Position: %.1f/%.1f (%.1f%%)",
              position_secs, duration_secs, progress_percent);
          }

          // Create a temporary buffer to hold the formatted text.
          char buffer[32];
          snprintf(buffer, sizeof(buffer), "%02d:%02d / %02d:%02d",
                   pos_min, pos_sec, dur_min, dur_sec);

          // Push the formatted string to the LVGL label
          lv_label_set_text(id(track_time_label_overlay), buffer);

  - id: handle_media_playing
    then:
      - lambda: 'ESP_LOGI("actions_media", "Media started playing.");'
      #- lvgl.page.show: page_media_overlay

  - id: handle_media_announcement
    then:
      - lambda: 'ESP_LOGI("actions_media", "An announcement is playing.");'

  - id: handle_media_paused
    then:
      - lambda: 'ESP_LOGI("actions_media", "Media paused playing.");'
      # TODO: Display a paused icon overlay.

  - id: handle_media_stopped
    then:
      - lambda: 'ESP_LOGI("actions_media", "Media stopped playing.");'
      # TODO: Display a stopped icon overlay.

  - id: handle_media_volume_muted
    then:
      - lambda: |-
          ESP_LOGI("actions_media", "Muted.");
      # TODO: Add a mute icon to the media pages?
      - lvgl.slider.update:
          id: volume_control_widget
          value: 0
      - lvgl.label.update:
          id: volume_text
          text: "Mute"

  - id: handle_media_volume_unmuted
    then:
      - lambda: |-
          ESP_LOGI("actions_media", "Unmuted.");
          id(handle_media_volume_changed)->execute(id(current_volume));

  - id: handle_media_volume_changed
    parameters:
      volume: float
    then:
      - lambda: |-
          ESP_LOGI("actions_media", "Current volume: %.1f%%", volume * 100.0);
          id(current_volume) = volume;
      - lvgl.slider.update:
          id: volume_control_widget
          value: !lambda 'return (volume * 100);'
      - lvgl.label.update:
          id: volume_text
          text:
            format: "Vol: %.0f%%"
            args: [ "volume * 100" ]

  - id: handle_media_track_changed
    parameters:
      track_name: std::string
    then:
      - lambda: |-
          ESP_LOGD("actions_media", "Music track: %s", track_name.c_str());
      - lvgl.label.update:
          id: track_name_label_overlay
          text: !lambda 'return track_name.empty() ? "Unknown Track" : track_name;'
      - lvgl.label.update:
          id: track_name_label_controls
          text: !lambda 'return track_name.empty() ? "Unknown Track" : track_name;'

  - id: handle_media_artist_changed
    parameters:
      artist_name: std::string
    then:
      - lambda: |-
          ESP_LOGD("actions_media", "Music artist: %s", artist_name.c_str());
      - lvgl.label.update:
          id: track_artist_label_overlay
          text: !lambda 'return artist_name.empty() ? "Unknown Artist" : artist_name;'
      - lvgl.label.update:
          id: track_artist_label_controls
          text: !lambda 'return artist_name.empty() ? "Unknown Artist" : artist_name;'

  - id: handle_media_album_changed
    parameters:
      album_name: std::string
    then:
      - lambda: |-
          ESP_LOGD("actions_media", "Music album: %s", album_name.c_str());
      - lvgl.label.update:
          id: track_album_label_overlay
          text: !lambda 'return album_name.empty() ? "Unknown Album" : album_name;'
      - lvgl.label.update:
          id: track_album_label_controls
          text: !lambda 'return album_name.empty() ? "Unknown Album" : album_name;'

  - id: handle_playlist_shuffle
    parameters:
      shuffle: bool
    then:
      - logger.log:
          format: "Playlist shuffle: %s"
          args: [ 'shuffle ? "true" : "false"' ]
      - lvgl.label.update:
          id: label_playlist_shuffle
          text: !lambda |-
            if (shuffle) {
              return "${icon_shuffle}";
            } else {
              return "${icon_shuffle_disabled}";
            }
      - homeassistant.service:
          service: media_player.shuffle_set
          data:
            entity_id: !lambda 'return id(preference_media_player_entity).state;'
            shuffle: !lambda 'return shuffle;'

  - id: play_playlist
    parameters:
      media_id: std::string
      shuffle: bool
    then:
      - if:
          condition:
            lambda: 'return !media_id.empty();'
          then:
            - script.execute:
                id: handle_playlist_shuffle
                shuffle: !lambda 'return id(setting_playlist_shuffle).state;'
            - logger.log:
                format: "Playing playlist: %s"
                args: [ "media_id.c_str()" ]
            - homeassistant.service:
                service: music_assistant.play_media
                data:
                  entity_id: !lambda 'return id(preference_media_player_entity).state;'
                  media_id: !lambda 'return media_id.c_str();'
                  media_type: playlist
                  enqueue: replace

# vim: set tabstop=2 shiftwidth=2 expandtab:
