# This unit connects the UI and the media player.
# It does not directly reference the media player entity, as both a local
# sendspin player and a remote HA media player are supported. Instead, scripts
# are used to abstract the API.
# The `handle_media_*` scripts are used to provide data _to_ the UI.
# The `set_media_*` scripts are used to send commands to the media player.

globals:
  - id: current_volume
    type: float
    initial_value: '0.5'  # Default fallback volume
  - id: artwork_invalid
    type: bool
    initial_value: 'true'
  - id: is_media_playing
    type: bool
    initial_value: 'false'
  - id: last_posted_position_secs
    type: int
    initial_value: '-1'
  - id: last_posted_duration_secs
    type: int
    initial_value: '-1'

select:
  - platform: template
    id: current_media_type
    internal: true
    optimistic: true
    options:
      - "none"
      - "music"
      - "audiobook"
      - "podcast"
      - "other"
    initial_option: "none"
    on_value:
      - text_sensor.template.publish:
          id: public_current_media_type
          state: !lambda 'return x;'

text_sensor:
  # A read-only copy of the current_media_type, published to HA.
  - platform: template
    id: public_current_media_type
    name: "Current Media Type"
    icon: "mdi:music"
    entity_category: diagnostic

text:
  - platform: template
    name: "Music Assistant Media Player Entity"
    id: preference_media_player_entity
    entity_category: config
    mode: text
    initial_value: "${mediaplayer}"
    restore_value: true
    set_action:
      - lambda: |-
          if (x.empty() || x == id(preference_media_player_entity).state) {
            // It's good, but nothing needs to change.
            id(preference_media_player_entity).publish_state(x);
            return;
          }
          if (!x.starts_with("media_player.")) {
            // It's bad, reject it. Don't need to reboot.
            ESP_LOGW("actions_time", "Rejecting invalid media_player entity; must start with \"media_player.\"; found: %s", x.c_str());
            id(preference_media_player_entity).publish_state(id(preference_media_player_entity).state);
            return;
          }
          // New value accepted, ask for a reboot.
          id(preference_media_player_entity).publish_state(x);
          ESP_LOGI("actions_media", "New media_player entity: %s. Will request reboot.", x.c_str());
          id(slow_trigger_reboot_sequence)->execute();

esphome:
  on_boot:
    # HA sensors setup runs at AFTER_CONNECTION (100). So long as we run after
    # DATA (600), we should be good.
    - priority: 300
      then:
        # Media Player Entity
        - lambda: |-
            // Static as set_entity_id takes the c_str pointer.
            static const std::string new_entity = id(preference_media_player_entity).state;
            if (!new_entity.empty()) {
              id(set_mediaplayer_entity_id)->execute(new_entity.c_str());
              id(preference_media_player_entity).publish_state(new_entity);
            }
        - script.execute: update_playlist_labels

script:
  - id: delayed_condition_album_art_placeholder
    mode: restart
    then:
      - lambda: 'id(artwork_invalid) = true;'
      - delay: 3s
      - if:
          condition:
            lambda: 'return id(artwork_invalid);'
          then:
            - logger.log: "Timer expired. Clearing old album artwork."
            - script.execute: handle_media_album_art_display_placeholder

  - id: handle_media_album_art_display_placeholder
    then:
      - lvgl.image.update:
          id: album_cover_image_overlay
          src: album_placeholder

  - id: handle_media_album_art_display
    parameters:
      art_source: esphome::image::Image*
    then:
      - lambda: 'id(artwork_invalid) = false;'
      - if:
          condition:
            lambda: 'return id(album_art_preference).state;'
          then:
            - lambda: |-
                ESP_LOGD("actions_media", "Album art downloaded!");
            - lvgl.image.update:
                id: album_cover_image_overlay
                src: !lambda "return art_source;"
          else:
            - script.execute: handle_media_album_art_display_placeholder

  - id: handle_media_progress
    parameters:
      position_secs: float
      duration_secs: float
    then:
      - lambda: |-
          if (position_secs == id(last_posted_position_secs)
              && duration_secs == id(last_posted_duration_secs)) {
            return;
          }
          if (duration_secs != id(last_posted_duration_secs)) {
            ESP_LOGD("actions_media", "New track duration: %.1f", duration_secs);
          }
          id(last_posted_position_secs) = position_secs;
          id(last_posted_duration_secs) = duration_secs;

          float progress_percent =
            duration_secs > 0.0 ? (position_secs / duration_secs * 100.0) : 0.0;
          lv_arc_set_value(id(track_progress_arc_overlay), progress_percent);

          // --- FORMAT AND UPDATE THE TEXT LABEL ---
          // Break down position into minutes and seconds
          int pos_hours = (int)position_secs / 3600;
          int pos_min = ((int)position_secs % 3600) / 60;
          int pos_sec = (int)position_secs % 60;

          // Break down duration into minutes and seconds
          int dur_hours = (int)duration_secs / 3600;
          int dur_min = ((int)duration_secs % 3600) / 60;
          int dur_sec = (int)duration_secs % 60;
          if (pos_sec % 10 == 0) {
            ESP_LOGD("actions_media", "Position: %.1f/%.1f (%.1f%%)",
              position_secs, duration_secs, progress_percent);
          }

          // Create a temporary buffer to hold the formatted text.
          char buffer[32];
          if (dur_hours > 0) {
            snprintf(buffer, sizeof(buffer), "%02d:%02d:%02d / %02d:%02d:%02d",
                     pos_hours, pos_min, pos_sec, dur_hours, dur_min, dur_sec);
          } else {
            snprintf(buffer, sizeof(buffer), "%02d:%02d / %02d:%02d",
                     pos_min, pos_sec, dur_min, dur_sec);
          }

          // Push the formatted string to the LVGL label
          lv_label_set_text(id(overlay_track_time_label), buffer);
          lv_label_set_text(id(controls_track_time_label), buffer);
          lv_label_set_text(id(time_track_time_label), buffer);

  - id: handle_media_playing
    then:
      - lambda: |-
          bool was_playing = id(is_media_playing);
          id(is_media_playing) = true;
          ESP_LOGI("actions_media", "Media started playing.");
          if (!was_playing) {  // don't reset if already playing
            id(handle_media_sleep_timer_maybe_restart)->execute();
          }
      - lvgl.label.update:
          id:
            - overlay_huge_play_pause_indicator
          hidden: true
      - lvgl.label.update:
          id:
            - overlay_play_pause_indicator_label
            - controls_play_pause_indicator_label
            - time_play_pause_indicator_label
          text: "${icon_play}"
          hidden: false
      # TODO: consider this, if we don't get triggered every track change
      # - script.execute: reset_idle_timer

  - id: handle_media_announcement
    then:
      - lambda: |-
          ESP_LOGI("actions_media", "An announcement is playing.");
      # Reset the idle timer; the screen will wake up if it was off, and after
      # a delay, we'll go to the appropriate idle page, unless the user does
      # something else.
      - script.execute: reset_idle_timer

  - id: handle_media_paused
    then:
      - lambda: |-
          ESP_LOGI("actions_media", "Media paused playing.");
          id(is_media_playing) = false;
          id(media_sleep_timer)->stop();
      # Display a paused icon overlay.
      - lvgl.label.update:
          id:
            - overlay_huge_play_pause_indicator
            - overlay_play_pause_indicator_label
            - controls_play_pause_indicator_label
            - time_play_pause_indicator_label
          text: "${icon_pause}"
          hidden: false

  - id: handle_media_stopped
    then:
      - lambda: |-
          ESP_LOGI("actions_media", "Media stopped playing.");
          id(is_media_playing) = false;
          id(media_sleep_timer)->stop();
      # Display a stopped icon overlay.
      - lvgl.label.update:
          id:
            - overlay_huge_play_pause_indicator
            - overlay_play_pause_indicator_label
            - controls_play_pause_indicator_label
            - time_play_pause_indicator_label
          # Always use pause, as it typically says stopped even when pausing.
          #text: "${icon_stop}"
          text: "${icon_pause}"
          hidden: false

  - id: handle_media_volume_muted
    then:
      - lambda: |-
          ESP_LOGI("actions_media", "Muted.");
          if (id(current_media_type).current_option() == "audiobook") {
            ESP_LOGI("actions_media", "Auto-pausing audiobook on mute.");
            id(set_media_pause)->execute();
          }
      # TODO: Add a mute icon to the media pages?
      - lvgl.slider.update:
          id: volume_control_widget
          value: 0
      - lvgl.label.update:
          id: volume_text
          text: "Mute"

  - id: handle_media_volume_unmuted
    then:
      - lambda: |-
          ESP_LOGI("actions_media", "Unmuted.");
          id(handle_media_volume_changed)->execute(id(current_volume));

  - id: handle_media_volume_changed
    parameters:
      volume: float
    then:
      - lambda: |-
          ESP_LOGI("actions_media", "Current volume: %.1f%%", volume * 100.0);
          id(current_volume) = volume;
      - lvgl.slider.update:
          id: volume_control_widget
          value: !lambda 'return (volume * 100);'
      - lvgl.label.update:
          id: volume_text
          text:
            format: "Vol: %.0f%%"
            args: [ "volume * 100" ]

  - id: media_sleep_timer
    mode: restart
    then:
      - delay: !lambda |-
          int sleep_timer_mins = (id(current_media_type).current_option() == "audiobook")
            ? id(preference_sleep_timer_audiobook_mins).state
            : id(preference_sleep_timer_music_mins).state;
          ESP_LOGI("actions_media", "Sleep timer [re-]starting: %d minutes.", sleep_timer_mins);
          return (uint32_t) (sleep_timer_mins * 60.0f * 1000.0f);
      - lambda: |-
          ESP_LOGI("actions_media", "Sleep timer expired. Pausing playback.");
          id(set_media_pause)->execute();

  - id: handle_media_sleep_timer_maybe_restart
    then:
      - lambda: |-
          const bool is_media_audiobook = id(current_media_type).current_option() == "audiobook";
          bool start_sleep_timer = id(is_media_playing)
            && (
              (is_media_audiobook && id(preference_sleep_timer_audiobook_mins).state > 0)
              || (!is_media_audiobook && id(preference_sleep_timer_music_mins).state > 0)
            );
          if (start_sleep_timer) {
            id(media_sleep_timer)->execute();
          } else if (id(media_sleep_timer).is_running()) {
            ESP_LOGI("actions_media", "Sleep timer cancelled.");
            id(media_sleep_timer)->stop();
          }

  - id: handle_media_content_id_change
    parameters:
      content_id: std::string
    then:
      - lambda: |-
          ESP_LOGD("actions_media", "Media Content Id: %s", content_id.c_str());
          const std::string prev_media_type = id(current_media_type).current_option();
          const bool was_audiobook = prev_media_type == "audiobook";

          // Examples:
          //   library://track/1234
          //   foo-aBcDeF12://audiobook/1234
          constexpr std::string_view delim = "://";
          size_t start_pos = content_id.find(delim);
          std::string_view new_media_type;
          if (start_pos == std::string::npos) {
            new_media_type = "none";
          } else {
            start_pos += delim.length();
            size_t end_pos = content_id.find("/", start_pos);
            std::string_view component;
            if (end_pos == std::string::npos) {
              component = content_id.substr(start_pos);
            } else {
              component = content_id.substr(start_pos, end_pos - start_pos);
            }
            if (component == "track" || component == "radio"
                || component == "album" || component == "artist"
                || component == "playlist" || component == "collection") {
              new_media_type = "music";
            } else if (component == "audiobook") {
              new_media_type = "audiobook";
            } else if (component.find("podcast") != std::string::npos) {
              new_media_type = "podcast";
            } else {
              new_media_type = "other";
            }
          }
          if (new_media_type != prev_media_type) {
            id(current_media_type).make_call().with_option(
                new_media_type.data(), new_media_type.size()).perform();

            // For non-sendspin, clear stale media labels. Home Assistant
            // should re-populate them, as they will have changed, and should
            // be triggered following this media_content_id execution. For
            // sendspin, they are reliably sent, and not in lock-step with the
            // HA media_content_id, so skip it.
            constexpr std::string_view enable_str = "${enable_sendspin}";
            if constexpr (enable_str == "false" || enable_str == "False"
                          || enable_str == "0") {
              id(handle_reset_media_metadata)->execute();
            }

            // Content type changed, reset timer.
            id(handle_media_sleep_timer_maybe_restart)->execute();
          }


  - id: handle_reset_media_metadata
    then:
      - script.execute:
          id: delayed_condition_album_art_placeholder
      - script.execute:
          id: handle_media_track_changed
          track_name: ""
      - script.execute:
          id: handle_media_artist_changed
          artist_name: ""
      - script.execute:
          id: handle_media_album_changed
          album_name: ""

  - id: handle_media_track_changed
    parameters:
      track_name: std::string
    then:
      - lambda: |-
          ESP_LOGD("actions_media", "Music track: %s", track_name.c_str());
      - lvgl.label.update:
          id:
            - overlay_track_name_label
            - controls_track_name_label
            - time_track_name_label
          text: !lambda |-
            return track_name.substr(0, 80);
          anim_duration: !lambda |-
            return std::max<int>(8000, track_name.substr(0, 80).length() * 200);

  - id: handle_media_artist_changed
    parameters:
      artist_name: std::string
    then:
      - lambda: |-
          ESP_LOGD("actions_media", "Music artist: %s", artist_name.c_str());
      - lvgl.label.update:
          id:
            - overlay_track_artist_label
            - controls_track_artist_label
            - time_track_artist_label
          text: !lambda |-
            return artist_name.substr(0, 80);
          anim_duration: !lambda |-
            return std::max<int>(8000, artist_name.substr(0, 80).length() * 200);

  - id: handle_media_album_changed
    parameters:
      album_name: std::string
    then:
      - lambda: |-
          ESP_LOGD("actions_media", "Music album: %s", album_name.c_str());
      - lvgl.label.update:
          id:
            - overlay_track_album_label
            - controls_track_album_label
            - time_track_album_label
          text: !lambda |-
            return album_name.substr(0, 80);
          anim_duration: !lambda |-
            return std::max<int>(8000, album_name.substr(0, 80).length() * 200);

  - id: handle_playlist_shuffle
    parameters:
      shuffle: bool
    then:
      - logger.log:
          format: "Playlist shuffle: %s"
          args: [ 'shuffle ? "true" : "false"' ]
      - lvgl.label.update:
          id: label_playlist_shuffle
          text: !lambda |-
            if (shuffle) {
              return "${icon_shuffle}";
            } else {
              return "${icon_shuffle_disabled}";
            }
      - homeassistant.service:
          service: media_player.shuffle_set
          data:
            entity_id: !lambda 'return id(preference_media_player_entity).state;'
            shuffle: !lambda 'return shuffle;'

  - id: update_playlist_labels
    then:
      - if:
          condition:
            lambda: 'return id(setting_playlist_1_name).state.empty() || id(setting_playlist_1_name).state == " ";'
          then:
            - lvgl.label.update:
                id: playlist_1_label
                text: !lambda 'return id(setting_playlist_1).state;'
          else:
            - lvgl.label.update:
                id: playlist_1_label
                text: !lambda 'return id(setting_playlist_1_name).state;'
      - if:
          condition:
            lambda: 'return id(setting_playlist_2_name).state.empty() || id(setting_playlist_2_name).state == " ";'
          then:
            - lvgl.label.update:
                id: playlist_2_label
                text: !lambda 'return id(setting_playlist_2).state;'
          else:
            - lvgl.label.update:
                id: playlist_2_label
                text: !lambda 'return id(setting_playlist_2_name).state;'
      - if:
          condition:
            lambda: 'return id(setting_playlist_3_name).state.empty() || id(setting_playlist_3_name).state == " ";'
          then:
            - lvgl.label.update:
                id: playlist_3_label
                text: !lambda 'return id(setting_playlist_3).state;'
          else:
            - lvgl.label.update:
                id: playlist_3_label
                text: !lambda 'return id(setting_playlist_3_name).state;'


  - id: play_playlist
    parameters:
      media_id: std::string
      shuffle: bool
    then:
      - if:
          condition:
            lambda: 'return !media_id.empty() && media_id != " ";'
          then:
            if:
              condition:
                lambda: 'return media_id.starts_with("script.");'
              then:
                - logger.log:
                    format: "Triggering script: %s"
                    args: [ "media_id.c_str()" ]
                - homeassistant.service:
                    service: !lambda 'return media_id.c_str();'
                    data: {}
              else:
                  - script.execute:
                      id: handle_playlist_shuffle
                      shuffle: !lambda 'return id(setting_playlist_shuffle).state;'
                  - logger.log:
                      format: "Playing playlist: %s"
                      args: [ "media_id.c_str()" ]
                  - homeassistant.service:
                      service: music_assistant.play_media
                      data:
                        entity_id: !lambda 'return id(preference_media_player_entity).state;'
                        media_id: !lambda 'return media_id.c_str();'
                        media_type: playlist
                        enqueue: replace
      - script.execute: navigate_to_idle

# vim: set tabstop=2 shiftwidth=2 expandtab:
