esphome:
  friendly_name: "${friendly_name}"
  name: "${name}"
  comment: "${comment}"
  min_version: 2026.6.0

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API.
# Top-level config should establish an encryption key.
api:

# Enable OTA updates.
# Top-level config should establish an ota password.
ota:
  - platform: esphome

time:
  - platform: homeassistant
    id: ha_time
    on_time:
      - seconds: /1
        then:
          - script.execute: update_time_labels

text_sensor:
  - platform: version
    name: "ESPHome Version"

  - platform: debug
    reset_reason:
      name: "Reset Reason"

binary_sensor:
  - platform: status
    name: "Connection Status"

button:
  - platform: restart
    name: "Restart"
    id: re_start
    entity_category: diagnostic

debug:
  update_interval: 60s

sensor:
  # Free memory info
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"

# vim: set tabstop=2 shiftwidth=2 expandtab:
