substitutions:
  font: gfonts://Roboto

  # http://materialdesignicons.com/cdn/7.4.47/
  # http://materialdesignicons.com/cdn/7.4.47/fonts/materialdesignicons-webfont.ttf
  icons_font: "https://github.com/Templarian/MaterialDesign-Webfont/raw/refs/heads/master/fonts/materialdesignicons-webfont.ttf"

  # font_mdi_top
  icon_wifi: "\U000F05A9"

  # font_mdi_time
  icon_clock: "\U000F00F0"
  icon_thermo_outside: "\U000F18D7"
  icon_thermo_inside: "\U000F0F55"
  icon_battery: "\U000F0079"

  # font_mdi_media
  icon_play_pause: "\U000F040E"
  icon_previous: "\U000F04AE"
  icon_next: "\U000F04AD"
  icon_shuffle: "\U000F049F"
  icon_shuffle_disabled: "\U000F049E"

# Font definition
font:
  - id: font_mdi_top
    file: ${icons_font}
    size: 16
    glyphs:
      - "${icon_wifi}"

  - id: font_mdi_time
    file: ${icons_font}
    size: 24
    glyphs:
      - "${icon_clock}"
      - "${icon_thermo_inside}"
      - "${icon_thermo_outside}"
      - "${icon_battery}"

  - id: font_mdi_media
    file: ${icons_font}
    size: 44
    glyphs:
      - "${icon_play_pause}"
      - "${icon_previous}"
      - "${icon_next}"
      - "${icon_shuffle}"
      - "${icon_shuffle_disabled}"

  - id: theme_font_small
    file: ${font}
    size: 14
    glyphsets:
      - GF_Latin_Core
      - GF_Greek_Core
      - GF_Cyrillic_Core

  - id: theme_font_normal
    file: ${font}
    size: 20
    glyphsets:
      - GF_Latin_Core
      - GF_Greek_Core
      - GF_Cyrillic_Core

  - id: theme_font_large
    file: ${font}
    size: 28
    glyphsets:
      - GF_Latin_Core
      - GF_Greek_Core
      - GF_Cyrillic_Core

# vim: set tabstop=2 shiftwidth=2 expandtab:
