substitutions:
  font: gfonts://Roboto

  # http://materialdesignicons.com/cdn/7.4.47/
  # http://materialdesignicons.com/cdn/7.4.47/fonts/materialdesignicons-webfont.ttf
  icons_font: "https://github.com/Templarian/MaterialDesign-Webfont/raw/refs/heads/master/fonts/materialdesignicons-webfont.ttf"

  # font_mdi_top
  icon_wifi: "\U000F05A9"
  icon_wifi_disconnected: "\U000F092F" # mdi:wifi-strength-outline
  icon_battery: "\U000F0079"           # mdi:battery
  icon_battery_20: "\U000F007B"        # mdi:battery-20
  icon_battery_50: "\U000F007E"        # mdi:battery-50
  icon_battery_charging: "\U000F0084"  # mdi:battery-charging

  # font_mdi_time
  icon_thermo_outside: "\U000F18D7"    # mdi:sun-thermometer-outline
  icon_thermo_inside: "\U000F0F55"     # mdi:home-thermometer-outline

  # font_mdi_light_fan
  icon_lightbulb: "\U000F0335"  # mdi-lightbulb
  icon_fan: "\U000F0210"  # mdi-fan

  # font_mdi_media_large
  icon_play: "\U000F040A"  # mdi:play
  icon_pause: "\U000F03E4"  # mdi:pause
  icon_stop: "\U000F04DB"  # mdi:stop

  # font_mdi_media
  icon_play_pause: "\U000F040E"  # mdi:play-pause
  icon_previous: "\U000F04AE"
  icon_next: "\U000F04AD"
  icon_shuffle: "\U000F049F"
  icon_shuffle_disabled: "\U000F049E"

# Font definition
font:
  - id: font_7seg
    file: https://raw.githubusercontent.com/rbtdev/spiroplot/master/fonts/DSEG7/Classic-MINI/DSEG7ClassicMini-Bold.ttf
    size: 50
    glyphs: "0123456789:- "

  - id: font_mdi_top
    file: ${icons_font}
    size: 16
    glyphs:
      - "${icon_wifi}"
      - "${icon_wifi_disconnected}"
      - "${icon_battery}"
      - "${icon_battery_20}"
      - "${icon_battery_50}"
      - "${icon_battery_charging}"

  - id: font_mdi_time
    file: ${icons_font}
    size: 24
    glyphs:
      - "${icon_thermo_inside}"
      - "${icon_thermo_outside}"

  - id: font_mdi_light_fan
    file: ${icons_font}
    size: 44
    glyphs:
      - "${icon_lightbulb}"
      - "${icon_fan}"

  - id: font_mdi_media_large
    file: ${icons_font}
    size: 80
    glyphs:
      - "${icon_play}"
      - "${icon_pause}"
      - "${icon_stop}"

  - id: font_mdi_media
    file: ${icons_font}
    size: 44
    glyphs:
      - "${icon_play_pause}"
      - "${icon_previous}"
      - "${icon_next}"
      - "${icon_shuffle}"
      - "${icon_shuffle_disabled}"

  - id: theme_font_small
    file: ${font}
    size: 14
    glyphsets:
      - GF_Latin_Core
      - GF_Greek_Core
      - GF_Cyrillic_Core

  - id: theme_font_normal
    file: ${font}
    size: 20
    glyphsets:
      - GF_Latin_Core
      - GF_Greek_Core
      - GF_Cyrillic_Core

  - id: theme_font_large
    file: ${font}
    size: 28
    glyphsets:
      - GF_Latin_Core
      - GF_Greek_Core
      - GF_Cyrillic_Core

# vim: set tabstop=2 shiftwidth=2 expandtab:
