# The lvgl UI base

substitutions:
  # Defaults. Override in per-theme yaml.
  theme_font_color: 0x888888
  theme_font_color2: 0xff8888
  theme_bg_color: 0xffffff
  theme_accent_color: 0xFFFF00
  theme_accent_dark_color: 0x66CCFF
  theme_warning_color: 0xff0000
  theme_success_color: 0x00ff00

  ui_padding: 4
  ui_radius: 52
  ui_border: 2
  ui_border_pressed: 3

image:
  # Local file paths are relative to the top-level yaml, not this file.
  - platform: file
    id: bg_image_file
    file: ${repo_base_uri}/themes/${theme}/bg_360x360.png
    type: RGB565
    resize: ${screenheight}x${screenheight}
    transparency: alpha_channel

  # Add a static album cover placeholder
  - platform: file
    id: album_placeholder
    file: ${repo_base_uri}/themes/${theme}/album_360x360.png
    type: RGB565
    resize: ${screenheight}x${screenheight}
    transparency: alpha_channel

lvgl:
  # Display & touchscreen bindings happen in the device configs.

  color_depth: 16
  default_font: theme_font_normal

  style_definitions:
    - id: rsk_page_bg
      bg_color: ${theme_bg_color}

    - id: rsk_bg_accent
      bg_color: ${theme_accent_color}
      border_color: ${theme_accent_dark_color}

    - id: rsk_bg_accent_dark
      bg_color: ${theme_accent_dark_color}
      border_color: ${theme_accent_color}

    - id: rsk_bg_warning
      bg_color: ${theme_warning_color}
      border_color: ${theme_accent_color}

    - id: rsk_arc_accent
      arc_color: ${theme_accent_color}

    - id: rsk_arc_accent_dark
      arc_color: ${theme_accent_dark_color}

    - id: rsk_font_color
      text_color: ${theme_font_color}

    - id: rsk_font_color2
      text_color: ${theme_font_color2}

  # NOTE: Ideally, styles listed in this `theme` section would apply the named
  # styles by default, but it seems to be silently ignored. So, each widget
  # must explicitly name the style still. I leave them here for documentation,
  # and the hope of future success.
  theme:
    label:
      styles: rsk_font_color
      text_font: theme_font_normal
      align: CENTER
      text_align: CENTER
    button:
      styles: rsk_bg_accent
      bg_opa: COVER
      radius: ${ui_radius}
      border_width: ${ui_border}
      gesture_bubble: true
      pressed:
        styles: rsk_bg_accent_dark
        border_width: ${ui_border_pressed}

  styles: rsk_page_bg

  top_layer:
    widgets:
      - label:
          id: top_api_status_widget
          styles: rsk_font_color2
          text_font: font_mdi_top
          text: ${icon_wifi}
          hidden: true
          align: BOTTOM_MID
      - label:
          id: top_reboot_label
          styles: rsk_font_color
          text_font: theme_font_large
          text: "Reboot pending!"
          hidden: true
          align: TOP_MID
          y: 15%

script:
  - id: apply_theme_colors
    parameters:
      font_color: int
      font_color2: int
      bg_color: int
      accent_color: int
      accent_dark_color: int
      warning_color: int
      success_color: int
    # TODO: Fill this out.
    then: []
