# The lvgl UI base

substitutions:
  # Defaults. Override in per-theme yaml.
  theme_font_color: 0x888888
  theme_font_color2: 0xff8888
  theme_bg_color: 0xffffff
  theme_accent_color: 0xFFFF00
  theme_accent_dark_color: 0x66CCFF
  theme_warning_color: 0xff0000
  theme_success_color: 0x00ff00

  theme_button_bg_color: ${theme_accent_color}
  theme_button_border_color: ${theme_accent_dark_color}
  theme_button_pressed_bg_color: ${theme_accent_dark_color}
  theme_button_pressed_border_color: ${theme_accent_color}

  ui_padding: 4
  ui_radius: 52
  ui_border: 2
  ui_border_pressed: 3

image:
  # Local file paths are relative to the top-level yaml, not this file.
  - id: bg_image_file
    file: ${repo_base_uri}/themes/${theme}/bg_360x360.png
    type: RGB565
    resize: ${screenheight}x${screenheight}
    transparency: alpha_channel

  # Add a static album cover placeholder
  - id: album_placeholder
    file: ${repo_base_uri}/themes/${theme}/album_360x360.png
    type: RGB565
    resize: ${screenheight}x${screenheight}
    transparency: alpha_channel

lvgl:
  id: my_lvgl
  displays:
    - main_display
  touchscreens:
    - my_touchscreen

  # Add color depth specification - Arduino uses 16-bit
  color_depth: 16
  default_font: theme_font_normal

  on_swipe_right:
    - script.execute: navigate_right
  on_swipe_left:
    - script.execute: navigate_left

  top_layer:
    widgets:
      - label:
          id: top_api_status_widget
          text_font: font_mdi_top
          text: ${icon_wifi}
          hidden: true
          align: BOTTOM_MID
          text_align: right
          text_color: ${theme_font_color2}
