# This is an lvgl page directly.
# Script references should be primarily in actions_settings.yaml

id: page_settings
bg_color: ${theme_bg_color}
widgets:
  - image:
      id: bg_image_settings
      src: bg_image_file
      align: CENTER
      width: 100%
      height: 100%

  - label:
      text: "Settings"
      align: CENTER
      text_color: ${theme_font_color}
