substitutions:
  enable_sendspin: false

  # Where to pull image files from.
  # Override this in the outer layer to "./" to use local files.
  repo_base_uri: "https://raw.githubusercontent.com/magdalar/RedSmartKnob/main/RedSmartKnob"

  # Default theme. Override in caller.
  theme: "white"

  project_version: 2026.7.0

packages:
  app_esphome: !include esphome.yaml
  app_wifi: !include wifi.yaml
  # Logic for startup / boot time.
  app_startup: !include startup.yaml

  ######### SENDSPIN MODE ###########
  app_sendspin: !include ${ "sendspin.yaml" if enable_sendspin else "disabled.yaml" }
  app_album_art_sendspin: !include ${ "album_art_sendspin.yaml" if enable_sendspin else "disabled.yaml" }
  ######### END SENDSPIN MODE ###########

  ######### REMOTE MEDIAPLAYER MODE ###########
  app_mediaplayer: !include ${ "disabled.yaml" if enable_sendspin else "mediaplayer.yaml" }
  app_album_art_url: !include ${ "disabled.yaml" if enable_sendspin else "album_art_url.yaml" }
  ######### END REMOTE MEDIAPLAYER MODE ###########

  # User settings, exposed via Home Assistant
  app_user_settings: !include settings.yaml

  # UI font and icon definitions.
  app_fonts: !include fonts.yaml

  # The LVGL user interface definition
  app_lvgl: !include lvgl.yaml
  app_lvgl_page_time: !include lvgl_page_time.yaml
  app_lvgl_page_media_overlay: !include lvgl_page_media_overlay.yaml
  app_lvgl_page_media_playlists: !include lvgl_page_media_playlists.yaml
  app_lvgl_page_media_controls: !include lvgl_page_media_controls.yaml

  # The main UI loop and navigation logic
  app_ui_loop: !include ui_loop.yaml
  # Wiring for the `time` lvgl UI page.
  app_actions_time: !include actions_time.yaml
  # Wiring between the lvgl UI and the mediaplayer.
  app_actions_media: !include actions_media.yaml

  # Device-specific empty script stubs. Thes should be '!extend'ed in the
  # device-specific configs as appropriate.
  app_script_stubs: !include script_stubs.yaml

  # Theme modifications. Must come last.
  app_theme: !include themes/${theme}/theme.yaml
