substitutions:
  ### These are not user-configurable.
  imagewidth: 120
  imageheight: 120
  screenwidth: 360
  screenheight: 360
  
  # Where to pull image files from.
  # Override this in the outer layer to "./RedSmartKnob" to use local files.
  repo_base_uri: "https://raw.githubusercontent.com/magdalar/RedSmartKnob/main/RedSmartKnob"

  # Default theme. Override in caller.
  theme: "white"

  project_version: 2026.7.0
  
  pkg_sendspin: !include sendspin.yaml
  pkg_album_art_sendspin: !include album_art_sendspin.yaml
  pkg_mediaplayer: !include mediaplayer.yaml
  pkg_album_art_url: !include album_art_url.yaml

packages:
  ######### SENDSPIN MODE ###########
  sendspin: ${ pkg_sendspin if enable_sendspin else {} }
  album_art_sendspin: ${ pkg_album_art_sendspin if enable_sendspin else {} }
  ######### END SENDSPIN MODE ###########

  ######### REMOTE MEDIAPLAYER MODE ###########
  mediaplayer: ${ {} if enable_sendspin else pkg_mediaplayer }
  album_art_url: ${ {} if enable_sendspin else pkg_album_art_url }
  ######### END REMOTE MEDIAPLAYER MODE ###########

  esp_config: !include esp-config.yaml
  ha_config: !include ha-config.yaml
  # Logic for startup / boot time.
  startup: !include startup.yaml
  user_settings: !include settings.yaml
  # Touchscreen display initialization.
  display: !include display.yaml
  # UI font and icon definitions.
  fonts: !include fonts.yaml
  # The LVGL user interface definition
  lvgl: !include lvgl.yaml
  # The main UI loop and navigation logic
  ui_loop: !include ui_loop.yaml
  # Wiring for the `time` lvgl UI page.
  actions_time: !include actions_time.yaml
  # Wiring between the lvgl UI and the mediaplayer.
  actions_media: !include actions_media.yaml
  # Battery status
  battery: !include adc_battery.yaml
  # Rotary Knob
  rotary_knob: !include rotary_knob.yaml
  # drv2605: haptic feedback.
  drv2605: !include drv2605.yaml
  # TODO: Add the sd card if needed, otherwise just leave it out...
  #sd_card: !include RedSmartKnob/sd_card.yaml

  # Theme modifications. Must come last.
  theme: !include themes/${theme}/theme.yaml

# vim: set tabstop=2 shiftwidth=2 expandtab:
