# Started from from https://community.home-assistant.io/t/display-knob/905249/15 user trinitytest
# Switched to a sendspin player based on https://github.com/RealDeco/sendspin-guition/blob/main/Guition_Knob_v2.yaml
# TODO: If coming from a stopped/idle state, art, position and track duration stay unknown.
# TODO: Pausing goes to on_idle immediately.

substitutions:
  i2c_id: internal_i2c
  i2s_mclk_multiple: 256
  i2s_bps_speaker: 16bit
  #i2s_bps_mic: 16bit
  i2s_sample_rate_speaker: 16000
  #i2s_sample_rate_mic: 16000 # must be 16000 for voice_assistant to work(?)
  i2s_use_apll: true
  # Run the stack in psram -- required.
  task_stack_in_psram: True

i2s_audio:
  - id: i2s_output_id
    i2s_lrclk_pin: GPIO40
    i2s_bclk_pin: GPIO39

speaker:
  - platform: i2s_audio
    id: i2s_audio_speaker
    i2s_dout_pin: GPIO41
    i2s_audio_id: i2s_output_id
    dac_type: external
    timeout: never
    buffer_duration: 100ms
    channel: stereo

  - platform: mixer
    id: mixing_speaker
    task_stack_in_psram: ${task_stack_in_psram}
    output_speaker: i2s_audio_speaker
    num_channels: 2
    source_speakers:
      - id: announcement_speaker_mixer_input
        timeout: never
      - id: media_speaker_mixer_input
        timeout: never

  - platform: resampler
    id: media_speaker_resampling_input
    task_stack_in_psram: ${task_stack_in_psram}
    output_speaker: media_speaker_mixer_input

  - platform: resampler
    id: announcement_speaker_resampling_input
    task_stack_in_psram: ${task_stack_in_psram}
    output_speaker: announcement_speaker_mixer_input

sendspin:
  id: sendspin_hub
  task_stack_in_psram: ${task_stack_in_psram}

text_sensor:
  - platform: sendspin
    id: sendspin_title
    type: title
    on_value:
      - script.execute:
          id: handle_media_track_changed
          track_name: !lambda return x;

  - platform: sendspin
    id: sendspin_artist
    type: artist
    on_value:
      - script.execute:
          id: handle_media_artist_changed
          artist_name: !lambda return x;

  - platform: sendspin
    id: sendspin_album
    type: album
    on_value:
      - script.execute:
          id: handle_media_album_changed
          album_name: !lambda return x;

sensor:
  - platform: sendspin
    type: track_progress
    id: sendspin_progress
    update_interval: 1s
    on_value:
      - lambda: |-
          float pos_secs = x / 1000.0;
          float dur_secs = id(sendspin_duration).has_state() ? id(sendspin_duration).state / 1000.0 : 0.0;
          id(handle_media_progress)->execute(pos_secs, dur_secs);

  - platform: sendspin
    type: track_duration
    id: sendspin_duration
    on_value:
      - lambda: |-
          ESP_LOGD("sendspin", "New track duration: %d", id(sendspin_duration).state);


audio_file:

media_source:
  - platform: audio_file
    id: audio_file_announcement_source
  - platform: audio_http
    id: http_announcement_source
  - platform: audio_http
    id: http_media_source
  - platform: sendspin
    id: sendspin_media_source
    task_stack_in_psram: ${task_stack_in_psram}

globals:
  - id: sendspin_is_idle
    type: bool
    initial_value: 'false'
  - id: sendspin_volume
    type: float
    initial_value: '-1.0'

media_player:
  - platform: sendspin
    id: sendspin_group_media_player
    name: Sendspin Group Media Player
    # Prevent this from showing up in Home Assistant by default.
    # The user can still enable it, though they should use the Music Assistant
    # entity instead.
    disabled_by_default: true

  - platform: speaker_source
    name: Media Player
    id: external_media_player

    announcement_pipeline:
      speaker: announcement_speaker_mixer_input
      format: FLAC
      sample_rate: ${i2s_sample_rate_speaker}
      num_channels: 1
      sources:
        - audio_file_announcement_source
        - http_announcement_source

    media_pipeline:
      format: FLAC
      sample_rate: ${i2s_sample_rate_speaker}
      speaker: media_speaker_mixer_input
      num_channels: 2
      sources:
        - http_media_source
        - sendspin_media_source

    volume_increment: 0.05
    volume_min: 0.4
    volume_max: 0.85
    on_mute:
      - script.execute: handle_media_volume_muted
    on_unmute:
      - script.execute: handle_media_volume_unmuted
    on_volume:
      - lambda: |-
          if (abs(id(sendspin_volume) - x) >= 0.01) {
            id(sendspin_volume) = x;
            id(handle_media_volume_changed)->execute(x);
          }
    on_play:
      - lambda: 'id(sendspin_is_idle) = false;'
      - script.execute: handle_media_playing
    on_idle:
      - if:
          condition:
            lambda: 'return !id(sendspin_is_idle);'
          then:
            - lambda: 'id(sendspin_is_idle) = true;'
            - script.execute: handle_media_paused
    on_pause:
      - script.execute: handle_media_paused
    on_announcement:
      - script.execute: handle_media_announcement

script:
  - id: set_media_volume
    parameters:
        new_vol: float
    then:
      - media_player.volume_set:
          id: sendspin_group_media_player
          volume: !lambda 'return new_vol;'

  - id: set_media_volume_mute
    then:
      - media_player.mute:
          id: sendspin_group_media_player

  - id: set_media_volume_unmute
    then:
      - media_player.unmute:
          id: sendspin_group_media_player

  - id: set_media_play_pause
    then:
      - media_player.toggle:
          id: sendspin_group_media_player

  - id: set_media_next
    then:
      - media_player.next:
          id: sendspin_group_media_player

  - id: set_media_previous
    then:
      - media_player.previous:
          id: sendspin_group_media_player

# vim: set tabstop=2 shiftwidth=2 expandtab:
