number:
  - platform: template
    id: screen_timeout_seconds
    name: Screen timeout delay
    unit_of_measurement: "s"
    icon: "mdi:timer-outline"
    entity_category: config
    optimistic: true
    restore_value: true
    mode: box
    min_value: 15
    max_value: 3600
    step: 5
    initial_value: 60
    set_action:
      - script.execute: reset_idle_timer

  - platform: template
    id: idle_timeout_seconds
    name: Idle timeout delay
    unit_of_measurement: "s"
    icon: "mdi:timer-outline"
    entity_category: config
    optimistic: true
    restore_value: true
    mode: box
    min_value: 1
    max_value: 60
    step: 1
    initial_value: 10
    set_action:
      - script.execute: reset_idle_timer

text:
  - platform: template
    name: "Playlist 1"
    id: setting_playlist_1
    optimistic: true
    entity_category: config
    icon: "mdi:playlist-music"
    mode: text
    initial_value: "My Awesome Playlist"
    restore_value: true
    on_value:
      - lvgl.label.update:
          id: playlist_1_label
          text: !lambda 'return "Playlist 1:\n" + id(setting_playlist_1).state;'

  - platform: template
    name: "Playlist 2"
    id: setting_playlist_2
    optimistic: true
    entity_category: config
    icon: "mdi:playlist-music"
    mode: text
    initial_value: ""
    restore_value: true
    on_value:
      - lvgl.label.update:
          id: playlist_2_label
          text: !lambda 'return "Playlist 2:\n" + id(setting_playlist_2).state;'

  - platform: template
    name: "Playlist 3"
    id: setting_playlist_3
    optimistic: true
    entity_category: config
    icon: "mdi:playlist-music"
    mode: text
    initial_value: ""
    restore_value: true
    on_value:
      - lvgl.label.update:
          id: playlist_3_label
          text: !lambda 'return "Playlist 3:\n" + id(setting_playlist_3).state;'

select:
  - platform: template
    id: screen_rotation
    name: Screen Rotation
    icon: "mdi:rotate-left"
    entity_category: config
    optimistic: true
    restore_value: true
    options:
      - "0°"
      - "90°"
      - "180°"
      - "270°"
    initial_option: "0°"
    on_value:
      - if:
          condition:
            lambda: 'return x == "0°";'
          then:
            - lvgl.display.set_rotation: 0
      - if:
          condition:
            lambda: 'return x == "90°";'
          then:
            - lvgl.display.set_rotation: 90
      - if:
          condition:
            lambda: 'return x == "180°";'
          then:
            - lvgl.display.set_rotation: 180
      - if:
          condition:
            lambda: 'return x == "270°";'
          then:
            - lvgl.display.set_rotation: 270

  - platform: template
    name: "Idle Page Preference"
    id: idle_page_preference
    entity_category: config
    optimistic: true
    restore_value: true
    # NOTE: Optional pages should judiciously be added here, as if they're
    # disabled, the navigate_to logic will just confusingly default to the
    # first page.
    # TODO: Add a "time_or_media" option, e.g. if playing.
    options:
      - "time"
      - "media"
      - "playlists"
      - "light_fan"
    initial_option: "time"
    set_action:
      - script.execute: reset_idle_timer
    on_value:
      - logger.log:
          format: "Display preference changed to: %s"
          args: ["x.c_str()"]

switch:
  - platform: template
    name: "Playlist Shuffle"
    id: setting_playlist_shuffle
    icon: "mdi:album"
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_state:
      - script.execute:
          id: handle_playlist_shuffle
          shuffle: !lambda 'return x;'

  - platform: template
    name: "Display Album Art"
    id: album_art_preference
    icon: "mdi:album"
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    turn_on_action:
      - logger.log: "Artwork enabled"
    turn_off_action:
      - logger.log: "Artwork disabled"
      - script.execute:
          id: handle_media_album_art_display_placeholder
