globals:
  # api_ready indicates if HA is currently connected
  - id: api_ready
    type: bool
    initial_value: 'false'

esphome:
    on_boot:
        - priority: -100
          then:
            - delay: 300ms
            - light.turn_on:
                id: back_light
                brightness: 50%
            - script.execute: standby_screen_activity

wifi:
  on_connect:
    - delay: 1s

api:
  on_client_connected:
    - logger.log:
        format: "Client %s connected (IP: %s)"
        args: [ "client_info.c_str()", "client_address.c_str()" ]
    - if:
        condition:
          api.connected:
            state_subscription_only: true
        then:
          - lambda: |-
              ESP_LOGI("startup", "Home Assistant connected.");
              id(api_ready) = true;
  on_client_disconnected:
    - logger.log:
        format: "Client %s disconnected (IP: %s)"
        args: [ "client_info.c_str()", "client_address.c_str()" ]
    - if:
        condition:
          not:
            api.connected:
              state_subscription_only: true
        then:
          - lambda: |-
              ESP_LOGW("startup", "Home Assistant disconnected.");
              id(api_ready) = false;
