globals:
  # api_ready indicates if HA is currently connected
  - id: api_ready
    type: bool
    initial_value: 'false'

esphome:
    on_boot:
        - priority: -100
          then:
            - script.execute: update_time_format
            - delay: 300ms
            - script.execute:
                id: navigate_to
                target: !lambda 'return id(idle_page_preference).current_option();'

# TODO: If any runtime loads are needed, start them here.
#wifi:
#  on_connect:
#    - delay: 1s

api:
  on_client_connected:
    - logger.log:
        format: "Client %s connected (IP: %s)"
        args: [ "client_info.c_str()", "client_address.c_str()" ]
    - wait_until:
        condition:
          api.connected:
            state_subscription_only: true
    - lambda: |-
        ESP_LOGI("startup", "Home Assistant connected.");
        id(api_ready) = true;
        id(api_connected)->execute();
  on_client_disconnected:
    - logger.log:
        format: "Client %s disconnected (IP: %s)"
        args: [ "client_info.c_str()", "client_address.c_str()" ]
    - if:
        condition:
          not:
            api.connected:
              state_subscription_only: true
        then:
          - lambda: |-
              ESP_LOGW("startup", "Home Assistant disconnected.");
              id(api_ready) = false;
              id(api_disconnected)->execute();
