wifi:
  # Wifi ssdi & password established at outer layer.

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback"
    password: "fallback"

captive_portal:

# Supports flashing generic firmware, establishing wifi info via webserial.
improv_serial:

text_sensor:
  - platform: wifi_info
    ip_address:
     name: ESP IP Address

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    internal: true
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "% Signal"
    entity_category: "diagnostic"
    device_class: ""
    icon: mdi:wifi

# vim: set tabstop=2 shiftwidth=2 expandtab:
