substitutions:
  theme_font_color: 0x212529
  theme_font_color2: 0x6C7378
  theme_bg_color: 0xFFFFFF
  theme_accent_color: 0x2D6CDF
  theme_accent_dark_color: 0x4A5560
  theme_warning_color: 0xD64545
  theme_success_color: 0x6C7378

image:
  - id: !extend bg_image_file
    file: ${repo_base_uri}/themes/${theme}/bg_360x360.png
  - id: !extend album_placeholder
    file: ${repo_base_uri}/themes/${theme}/album_360x360.png
