substitutions:
  dev_has_battery: "true"

  ### These are not user-configurable.
  screenwidth: 360
  screenheight: 360

  # TODO: configure the microphone
  microphone_id: no_microphone_configured
  output_speaker_id: i2s_audio_speaker
  sample_rate_speaker: 16000
  task_stack_in_psram: True

  # Default theme. Override in caller.
  theme: "white"

packages:
  # Core device and chip configuration
  device: !include device.yaml
  # Speaker definition
  audio: !include audio.yaml
  # Touchscreen display initialization.
  display: !include display.yaml
  # Battery status
  battery: !include ${ "adc_battery.yaml" if dev_has_battery else "../../RedSmartKnob/disabled.yaml" }
  # Rotary Knob
  rotary_knob: !include rotary_knob.yaml
  # drv2605: haptic feedback.
  drv2605: !include drv2605.yaml
  # TODO: Add the sd card if needed, otherwise just leave it out...
  #sd_card: !include sd_card.yaml
  
  app_main: !include ../../../RedSmartKnob/main.yaml

# vim: set tabstop=2 shiftwidth=2 expandtab:
