substitutions:
  ### These are not user-configurable.
  screenwidth: 360
  screenheight: 360

  microphone_id: microphone_id
  output_speaker_id: i2s_audio_speaker
  sample_rate_speaker: 48000
  task_stack_in_psram: True

  # Where to pull image files from.
  # Override this in the outer layer to use local files.
  repo_base_uri: "https://raw.githubusercontent.com/magdalar/RedSmartKnob/main"

  # Default theme. Override in caller.
  theme: "white"

packages:
  # Core device and chip configuration
  device: !include device.yaml
  # Speaker definition
  audio: !include device/audio.yaml
  # Touchscreen display initialization.
  display: !include device/display.yaml
  # TODO: Add the sd card if needed, otherwise just leave it out...
  #sd_card: !include device/sd_card.yaml
  
  app_main: !include ../../RedSmartKnob/main.yaml

# vim: set tabstop=2 shiftwidth=2 expandtab:
