substitutions:
  theme_font_color: 0xffffff
  theme_font_color2: 0x888888

#image:
#  - id: !extend bg_image_file
#    file: https://raw.githubusercontent.com/magdalar/RedSmartKnob/main/themes/blue/bg_360x360.png
